### ISSUE TITLE
我做了一些修改！增加了塔罗牌今日运势牌组，抽取带有正逆位，jrrp每日只能有一个数值

### ISSUE THREAD

**Issue by LoranaAurelia** [HackerRouter/MCDR-Meow#1]
写的有点屎，但能用就行~
下面是代码：

# -*- coding: utf-8 -*-
from __future__ import division
from urllib.parse import quote

import random
import math
import datetime

HelpMessage = '''§e------喵喵喵喵喵~喵(つ≧▽≦)つ------
一个支持游戏内吸猫猫的插件
§a【格式说明】§r
§6.help§b -获取帮助信息
§6.jrrp§b -获取今日人品
§6.draw§b -抽牌
§6.afk§b -提示其他玩家你在挂机
§6.url§b -发送一个链接
§6.welcome set §e[0/1]§b -控制入服欢迎开关（默认开启）
§6.whitelist §e[add/remove] §d[PlayerName]§b -为某人加/减去白名单（须指定人)
§6.carpet §e[...] §d[...]§b -游戏内设置carpet特性开关（须指定人)
§6.mpch §b获取MCDR Pearl Cannon Helper的帮助信息
§e--------------------------'''

MPCHHelpMessage = '''========§6MCDR Pearl Cannon Helper§r========
.mpch 显示这条信息
.mpch calculate [< 珍珠初始速度(m/s) >]  [< 珍珠与TNT角度(>5,<20) >] -珍珠炮射程（单位:m)估算
§6想法提出者&公式贡献者：GhastRs'''

player_luck_values = {}

welcomerTrue = 1
op = 'HackerRouter'

tarot_cards = {
    "§e【1】  §6愚者": {
        "§b正位": "§6新开始§7, §6无畏冒险§7, §6自由精神",
        "§c逆位": "§6冲动§7, §6鲁莽§7, §6缺乏方向",
    },
    "§e【2】  §6魔术师": {
        "§b正位": "§6创造力§7, §6技能§7, §6潜能",
        "§c逆位": "§6欺诈§7, §6欺骗§7, §6幻觉",
    },
    "§e【3】  §6女祭司": {
        "§b正位": "§6直觉§7, §6神秘§7, §6潜在知识",
        "§c逆位": "§6隐藏的动机§7, §6秘密§7, §6自欺",
    },
    "§e【4】  §6皇后": {
        "§b正位": "§6母性§7, §6安慰§7, §6生育",
        "§c逆位": "§6依赖§7, §6过度保护§7, §6拒绝成长",
    },
    "§e【5】  §6皇帝": {
        "§b正位": "§6权威§7, §6稳定§7, §6纪律",
        "§c逆位": "§6强权§7, §6控制欲过强§7, §6僵化",
    },
    "§e【6】  §6教皇": {
        "§b正位": "§6智慧§7, §6慈悲§7, §6宽容",
        "§c逆位": "§6教条§7, §6虚伪§7, §6偏见",
    },
    "§e【7】  §6恋人": {
        "§b正位": "§6爱情§7, §6关系§7, §6结合",
        "§c逆位": "§6不和§7, §6冲突§7, §6错误的选择",
    },
    "§e【8】  §6战车": {
        "§b正位": "§6胜利§7, §6进展§7, §6自信",
        "§c逆位": "§6挫折§7, §6散乱§7, §6自负",
    },
    "§e【9】  §6力量": {
        "§b正位": "§6勇气§7, §6耐心§7, §6内在力量",
        "§c逆位": "§6恐惧§7, §6懦弱§7, §6自我怀疑",
    },
    "§e【10】§6隐者": {
        "§b正位": "§6内省§7, §6独处§7, §6沉思",
        "§c逆位": "§6孤立§7, §6冷漠§7, §6退缩",
    },
    "§e【11】§6命运之轮": {
        "§b正位": "§6运势§7, §6机遇§7, §6命运",
        "§c逆位": "§6意外§7, §6不可预测§7, §6不稳定",
    },
    "§e【12】§r正义": {
        "§b正位": "§6公平§7, §6平衡§7, §6正直",
        "§c逆位": "§6不公§7, §6失衡§7, §6冲动",
    },
    "§e【13】§6倒吊人": {
        "§b正位": "§6牺牲§7, §6悬停§7, §6观察",
        "§c逆位": "§6无动于衷§7, §6恶果§7, §6拖延",
    },
    "§e【14】§6死神": {
        "§b正位": "§6转变§7, §6结束§7, §6重生",
        "§c逆位": "§6抗拒改变§7, §6病态循环§7, §6恐惧",
    },
    "§e【15】§6节制": {
        "§b正位": "§6平衡§7, §6调和§7, §6耐心",
        "§c逆位": "§6极端§7, §6过度§7, §6失调",
    },
    "§e【16】§6恶魔": {
        "§b正位": "§6诱惑§7, §6束缚§7, §6物质主义",
        "§c逆位": "§6解放§7, §6戒除§7, §6觉醒",
    },
    "§e【17】§6塔": {
        "§b正位": "§6突变§7, §6破坏§7, §6启示",
        "§c逆位": "§6恐慌§7, §6逃避§7, §6压抑",
    },
    "§e【18】§6星星": {
        "§b正位": "§6希望§7, §6灵感§7, §6信任",
        "§c逆位": "§6失望§7, §6沮丧§7, §6不信任",
    },
    "§e【19】§6月亮": {
        "§b正位": "§6直觉§7, §6梦想§7, §6潜意识",
        "§c逆位": "§6混乱§7, §6欺骗§7, §6恐惧",
    },
    "§e【20】§6太阳": {
        "§b正位": "§6活力§7, §6成功§7, §6热情",
        "§c逆位": "§6过度自信§7, §6失望§7, §6无知",
    },
    "§e【21】§6审判": {
        "§b正位": "§6觉醒§7, §6复兴§7, §6救赎",
        "§c逆位": "§6拖延§7, §6拒绝改变§7, §6内疚",
    },
    "§e【22】§6世界": {
        "§b正位": "§6完成§7, §6整合§7, §6无拘无束",
        "§c逆位": "§6未完成§7, §6悬而未决§7, §6恐惧",
    },
}

def get_today():
    return datetime.date.today()

def get_jrrp(player):
    today = get_today()
    if player not in player_luck_values or player_luck_values[player]['date'] != today:
        player_luck_values[player] = {
            'value': random.randint(1, 100),
            'date': today
        }
    return player_luck_values[player]['value']

def draw_tarot_card():
    card_name = random.choice(list(tarot_cards.keys()))
    card_position = random.choice(["§b正位", "§c逆位"])
    card_meaning = tarot_cards[card_name][card_position]
    return f"{card_name}-{card_position}：{card_meaning}"

def work(server, info):
    global welcomerTrue
    finalString = info.content
    if info.is_player == 1:

      def on_player_joined(server, playername):
        if welcomerTrue == 1:
          result = 'tellraw @a {"text":"[猫猫] 欢迎' + playername + '加入游戏."}'
          server.execute(str(result))

def work(server, info):
  global welcomerTrue
  finalString = info.content
  if info.is_player == 1:
    if info.content.find('猫') > -1:
      randomText =['喵(つ≧▽≦)つ', '喵喵喵(≧▽≦)', '喵喵喵！', '喵喵喵~~', '喵？喵！']
      result = 'tellraw @a {"text":"§d§l[猫猫] §e' + random.choice(randomText) + '"}'
      server.execute(str(result))
    elif info.content.find('喵喵') > -1:
      randomText =['喵喵喵！你也是猫猫啊！']
      result = 'tellraw @a {"text":"§d§l[猫猫] §e' + random.choice(randomText) + '"}'
      server.execute(str(result))
    elif info.content == '.draw ' or info.content == '.draw':
      result = 'tellraw @a {"text":"§d§l[猫猫] §e未指定牌堆名."}'
      server.execute(str(result))
    elif info.content == '.draw 塔罗牌' or info.content == '.draw 大阿卡那' or info.content == '.draw Major' or info.content == '.draw major' or info.content == '.draw Tarot' or info.content == '.draw tarot':
      randomText =['§e【0】§b愚者-正位', '§e【0】§c愚者-逆位', '§e【1】§b魔术师-正位', '§e【1】§c魔术师-逆位', '§e【2】§b女祭司-正位', '§e【2】§c女祭司-逆位', '§e【3】§b女皇-正位', '§e【3】§c女皇-逆位', '§e【4】§b皇帝-正位', '§e【4】§c皇帝-逆位', '§e【5】§b教皇-正位', '§e【5】§c教皇-逆位', '§e【6】§b恋人-正位', '§e【6】§c恋人-逆位', '§e【7】§b战车-正位', '§e【7】§c战车-逆位', '§e【8】§b力量-正位', '§e【8】§c力量-逆位', '§e【9】§b隐者-正位', '§e【9】§c隐者-逆位', '§e【10】§b命运之轮-正位', '§e【10】§c命运之轮-逆位', '§e【11】§b正义-正位', '§e【11】§c正义-逆位', '§e【12】§b倒吊人-正位', '§e【12】§c倒吊人-逆位', '§e【13】§b死神-正位', '§e【13】§c死神-逆位', '§e【14】§b节制-正位', '§e【14】§c节制-逆位', '§e【15】§b恶魔-正位', '§e【15】§c恶魔-逆位', '§e【16】§b塔-正位', '§e【16】§c塔-逆位', '§e【17】§b星星-正位', '§e【17】§c星星-逆位', '§e【18】§b月亮-正位', '§e【18】§c月亮-逆位', '§e【19】§b太阳-正位', '§e【19】§c太阳-逆位', '§e【20】§b审判-正位', '§e【20】§c审判-逆位', '§e【21】§b世界-正位', '§e【21】§c世界-逆位']
      result = 'tellraw @a {"text":"§d§l【猫猫】 ' + info.player + '§e抽到的是: ' + random.choice(randomText) + '"}'
      server.execute(str(result))
    elif info.content == '.draw 小阿卡那' or info.content == '.draw Minor' or info.content == '.draw minor':
      randomText =['权杖', '星币', '圣杯', '宝剑']
      result = 'tellraw @a {"text":"§d§l【猫猫】 ' + info.player + '§e抽到的是: ' + random.choice(randomText) + '"}'
      server.execute(str(result))
    elif info.content == '.jrrp' or info.content == '.鸡肉肉皮':
      result = get_jrrp(info.player)
      server.execute(str('tellraw @a {"text":"§d§l【猫猫】 ' + info.player + '§e今天的人品值是: §b' + str(result) + '"}'))
    elif info.content == '.horoscope':
      fortune_categories = ["§5财运", "§5爱情", "§5工作", "§5人际", "§5健康"]
      horoscope_result = "\n§e-----运势-----"
      for category in fortune_categories:
        drawn_card = draw_tarot_card()
        horoscope_result += f"\n{category}：{drawn_card}"
      horoscope_result += "\n§e-------------"
      server.say(horoscope_result)
    elif info.content.startswith('.welcome set '):
      welcomerTrue = info.content[13:]
      try:
         welcomerTrue = int(welcomerTrue)
         if welcomerTrue == 1:
           server.execute(str('tellraw @a {"text":"§d§l【猫猫】 §e已将欢迎提示设为开启."}'))
         elif welcomerTrue == 0:
           server.execute(str('tellraw @a {"text":"§d§l【猫猫】 §e已将欢迎提示设为关闭."}'))
         else:
           server.execute(str('tellraw @a {"text":"§d§l【猫猫】 §e错误,非法数据，仅可输入0或1."}'))
      except:
           server.execute(str('tellraw @a {"text":"§d§l【猫猫】 §e错误,非法数据，必须为整数."}'))
    elif info.content.startswith('.url '):
    	result = info.content[5:]
    	server.execute(str('tellraw @a [{"text":"<' + info.player + '> "},{"text":"' + result + '","color":"blue","underlined":"true","clickEvent":{"action":"open_url","value":"' + result + '"}}]'))
    elif info.content == '.afk':
    	server.execute(str('tellraw @a {"text":"' + info.player + ' is afk-ing."}'))
    elif info.content.startswith('.whitelist add ') and info.player == op:
    	result = info.content[15:]
    	server.execute(str('whitelist add ' + result))
    elif info.content.startswith('.whitelist remove ') and info.player == op:
    	result = info.content[18:]
    	server.execute(str('whitelist remove ' + result))
    elif info.content.startswith('.carpet ') and info.player == op:
    	result = info.content[8:]
    	server.execute(str('carpet ' + result))
    elif info.content.find('大佬') > -1 and int(finalString.find('tamakoooo')) > -1:
    	server.execute(str('kick ' + info.player +' ...'))
    	server.tell('Planetes_','{"text":"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"}')

    elif info.content.startswith('.mpch'):
      if info.content.startswith('.mpch calculate'):
        pearlSpeed = int(info.content.split()[2])
        angle = math.ceil(float(info.content.split()[3]))
        finalValue = str(pearlSpeed * 100 * ( angle/100 + 1 ))
        server.say('MPCH的计算结果：' + finalValue + 'm.')
      else:
        server.say(MPCHHelpMessage)
    elif info.content.startswith('.help'):
      server.say(HelpMessage)

# MCDaemon
def onServerInfo(server, info):
	if info.isPlayer == 1:
		work(server, info)

# MCDReforged
def on_info(server, info):
	if info.is_player:
		work(server, info)

def on_load(server, old):
	server.add_help_message('.help', '多功能的聊天机器人')

**Comment by HackerRouter** [comment]
没想到老早以前用脚写的插件还有人看（
有时间的话我会更新到新版本的
